Update syntax.yml

diff --git a/.github/workflows/syntax.yml b/.github/workflows/syntax.yml
--- a/.github/workflows/syntax.yml
+++ b/.github/workflows/syntax.yml
@@ -37,7 +37,15 @@ jobs:
           fi
       
     - name: Lint Bash Scripts
-      run: find . -type f \( -name "*.sh" -o -exec grep -q -I1 '^#!.*\bbash\b' {} \; \) -print | xargs realpath | sed 's/^[^/]*//g' | grep '^/home/' | xargs shellcheck
+      run: |
+          find . -type f \( -name "*.sh" -o -exec grep -q -I1 '^#!.*\bbash\b' {} \; \) -print | xargs realpath | sed 's/^[^/]*//g' | grep '^/home/' | xargs shellcheck 2>&1 | tee /tmp/shellcheck.txt
+          if grep -q 'error:' /tmp/shellcheck.txt; then
+            echo "Shellcheck found errors!"
+            exit 1
+          else
+            echo "Bash scripts passed!"
+          fi
+          
     - name: Lint Perl Scripts
       run: find . -type f \( -name "*.pl" -o -name "*.pm" -o -exec grep -I1 '^#!.*\bperl\b' {} \; \) -print0 | xargs -0 realpath | xargs -0 -I {} perl -c {}
 
